### PR TITLE
Core Files/Testing Update and introduce adapter-core

### PR DESCRIPTION
**Pull request by Apollon77**
see https://forum.iobroker.net/post/237344 for more details

### CODE REVIEW

**Comment by frankjoke** [comment]
Ingo,
I posted yesterday an updated version of km200 which is passing all tests and using your newest tests but only on Travis, I removed appveyor because Travis can handle windows now as well!

As I mentioned, I will update ALL my adapters, but it will take some days because I test each of them!
km200  is finished and xs1 is also, bmw nearly finished, still working on radar2, broadlink2, systeminfo, statemachine, I need to setup a test machine for compact mode, can you help?
xs1, bmw, km200, broadlink2, systeminfo and statemachine schould work on compact mode. radar & rdar2 not.

It would be good to communicate new test files and test conditions instead of creating pull requests.
It took me yesterday a day to understand the requirements because when I applied your changes on bmw they did not work on km200!
Tests for all my but bmw adapters were failing even if I copied your changes!
So I had to find out the hard way, why cannot you send a mail to developers (you have them from the json's) and tell them that new test/adapter-core/... are to be used?

p.s.: had other problems: How to update an iobroker installation to new scripts?
If I use new installation iobroker stop is working, but for my (some week olds) not, how can I update them without new installation? An `iobroker upgrade self` did not do it!
If I do iobroker stop it wont stop, it will need me to stop the service. But how can I update these to newests where it works? 

I DO NOT WANT TO REINSTALL IOBROKER 5 TIMES A DAY because I HAVE 5 SYSTEMS!

I also had problems using `iobroker url whatever` because it brought up 'EACCESS' errors on directories. Need to use 'sudo -u iobroker'...

Then I have a huge problem with Admin3. If I have it open for any test or production machine it gets very slow after (some) hours! Need to close the tab/browser and open it new again to be usable (using chrome on an 8-core).

By the way, have also a thank you: Thanks that you helped MathiasJ to resolve his problem with wrong version or Python because he could not install one of my adapters rightfully!

LG
Frank

**Comment by Apollon77** [comment]
> It would be good to communicate new test files and test conditions instead of creating pull requests.
So I had to find out the hard way, why cannot you send a mail to developers (you have them from the json's) and tell them that new test/adapter-core/... are to be used?

The reality and learing is: Noone reacts on emails, noone reads forum, only devs that "have some time" react on issues on GitHub, but 80% of the devs will review and accept/work with a PR because it is a very convenient way. The developer can still focus on the adapter development and do not need to take care of testing.
And 99% of the developers appreciate this "Service". If the PR is not helpful for you, you are free to decline it ... I don't care.

And yes Adapter testing sometimes is not that easy, especially when the adapter have special requirements, bust mostly it is identical. Else: Forum is the best place to discuss such problems and to share solutions.
For the other questions please start Forum thread because it is out of topic here.

**Comment by AlCalzone** [comment]
> How to update an iobroker installation to new scripts?

Take a look in the forum:
https://forum.iobroker.net/topic/20211/iobroker-installation-fixer-beta-verf%C3%BCgbar

> Need to use 'sudo -u iobroker'...

Not if your installation is up to the latest standards (fixer script)

> It would be good to communicate new test files and test conditions instead of creating pull requests.

Actually, creating pull requests allows us to also automatically test the changes on your repo, before requiring you to do any changes.

One more thing: Please stop blaming us for trying to improve and simplify things.  
1. The installer/fixer changes were necessary because the old way breaks stuff (with EACCESS errors) on new npm versions
2. The new `@iobroker/adapter-core` allows us to update the link to js-controller without bugging every developer to update his `utils.js` file
3. The new `@iobroker/testing` also allows us to update the default tests without having to update all test files in every adapter repo.

All those changes require some work now but greatly reduce the amount of work we and all developers have to do later. If you don't want these simplifications, don't use them.

For example, I ran the fixer script on my old installation from 2017, which was full of broken file permissions and required `sudo` to start and stop iobroker. 1 minute later, everything worked like a charm.

**Comment by frankjoke** [comment]
I am happy to use @iobroker/adapter-core (which I included already in most adapters) and also better testing.
Habe Appveyor von meisten Tests rausgeschmissen da Travis Windows jetzt kann, und schneller.

Install-fixer wird mal ausprobiert. Installiert er auch die neuen iobroker-scripts im /opt/iobroker-Verzeichnis?
Hab ihn auf dem Testsystem jetzt verwendet, hat geklappt nachdem ich den iobroker händisch mit `sudo systemctl stop iobroker.service` gestoppt habe (das script hat gemailt dass iobroker läuft und iobroker stop hat ja nicht funtioniert).

Werde die anderen Systeme auch 'updaten'.

Übrigens, wie erzeug ich die @xxx/yyy npm's von meinem github/yyy repo? Wollte das auch verwenden um einige repo's die ich immer verwende einzubinden anstatt die Dateien in jedes repo zu kopieren...

**Comment by frankjoke** [comment]
Man kann leider auf https://forum.iobroker.net/topic/20211/iobroker-installation-fixer-beta-verf%C3%BCgbar nicht posten, wollte da nur reinschreiben dass ich sowas eigentlich mit 'iobroker upgrade self' automatisch erwarte!

**Comment by frankjoke** [comment]
Nochwas, könnt ihr den Adapter-checker und die Testroutinen sysnchronisieren? Die Testroutinen spucken mehr Fehler aus wodurch Travis durchfällt und beim Adaptercheck wird nur ausgespuct dass Travis durchfällt!

p.s.: Habe gestern beim radar2-Adapter beim Test überall alles grün gehabt, heite krieg ich OSX v8 und v10 nicht durch, v6 geht. Fehler:
`
 1 failing
  1) Test radar2 adapter
       Test radar2 adapter: Check if adapter started:
      Uncaught AssertionError: expected 'Cannot check connection' to not equal 'Cannot check connection'
      + expected - actual
      at test/testAdapter.js:108:35
      at checkConnectionOfAdapter (test/testAdapter.js:18:17)
      at Timeout._onTimeout (test/testAdapter.js:28:17)
`

**Comment by Apollon77** [comment]
Posten im Diskussionsthread: https://forum.iobroker.net/topic/20212/diskussion-zum-neuen-installation-fixer (einfach den von Dir verlinkten Post lesen :-) )

Fehler beim testing: Link bitte

**Comment by Apollon77** [comment]
PS: Fehler radar2 liegt daran das der adapter schneller wieder beendet ist als das testing es prüfen kann das er gestartet ist. Daher wartet er immer weiter.
Grund zB https://travis-ci.org/frankjoke/ioBroker.radar2/jobs/503309201#L696

Optionen: Den "adapter started" check rausnehmen aus dem Testing oder sicherstellen da der adapter bei solchen Fehlern nicht stirbt

**Comment by AlCalzone** [comment]
Alternativ auf @iobroker/testing wechseln, das testet den Start anders.

**Comment by frankjoke** [comment]
AlCalzone, habe keine Ahnung von ts und 'unit'-testing! Brauich auch keinen Test der Adapter-Funktionen, das mach ich schon mit den Testsystemen un VSCode ode crome debug.
Ich will nur dass der Travis-Test durchläuft!

Bin ziemlich frustriert heute da ich V 1.0.0 von radar2 committed habe. Travis begann zu arbeiten und zeigte grün außer bei osx v8+v10. Habe osx ausgeschaltet und Travis lief durch in grün.

Habe dann noch spelling checks gemacht und zwei readme's für Englisch und Deutsch und Travis brachte rot bei Linux! Grund war dass adaper nicht normal beendet wurde, auch einige warnings waren aktiv wie no new entry for current version und `titleLang` missing.
Both are in the file :(

Nach weiteren kleinen Text-Änderungen zuerst: Adapter lief grün durch, warnings blieben!

Erschreckend.
Habe mir testPackageFiles (von dir beim anderen Adapter im pull request) angeschaut und alles ist rot (unter esLint). describe undefined ... wo ist describe definiert?
`
'use strict';

const expect = require('chai').expect;
const fs     = require('fs');

describe('Test package.json and io-package.json', () => {
    it('Test package files', done => {
`
 Was ist da faul?

**Comment by frankjoke** [comment]
By the way, Adapter-check https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/frankjoke/ioBroker.km200 shows all OK if Travis passes in green!

Why are things like testAdapter.js,  testPackageFiles.js or setup.js not available via @iobroker/testing?
I mean that only stub versions of the files are in the adapter and the real content is included via testing.
This could offload us to change adapters if testing procedures change!

**Comment by Apollon77** [comment]
Ooooohhk ... I try some answers (again totally wrong place here!! Forum would be much moe beneficial).

Describe methods and such come our of "Mocha" library.

The new testing is working differently so the "Old" files are named (and working) differently there. Please read READE from iobroker/testing lib.

Else the warnings are correct!!
1.) news are not in common- so wrong
2.) titleLang is an object with localized texts, so structure as with the news - so wrong

**Comment by Apollon77** [comment]
Ps: one additional note to appveyor vs Travis. Appveyor Runs a Full Windows environment while Travis is mainly using the Linux subsystem of a windows machine. So results may be different. For simple adapters it is ok to leave appveyor aside. The more special it is for os appveyor has still benefit

**Comment by frankjoke** [comment]
Ok, understand. Will check on that. I will close the pull request now because all ist implemented now.

**Pull request closed without merging**
